### ISSUE TITLE
Nodejs serverless: AppLambdaFunction is returning an error Role that I don’t understand or how to debug

### ISSUE THREAD

**Issue by diegoug** [VadymKhodak/django-aws-lambda#1]
Hello, I have followed your article where django is deployed on a derverless server but I get an error in a part that I do not understand, I don’t know how to debug and I don’t know how to fix it, please help!

https://blog.vadymkhodak.com/deploy-django-app-on-aws-lambda-using-serverless-part-1

the error is this:

AppLambdaFunction
CREATE_FAILED
Properties validation failed for resource AppLambdaFunction with message: #/Role: failed validation constraint for keyword [pattern]

Traceback:
$ serverless deploy -s production
Serverless: Deprecation warning: Support for “package.include” and “package.exclude” will be removed with next major release. Please use “package.patterns” instead
More Info: /framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
“provider.role” → “provider.iam.role”
More Info: /framework/docs/deprecations/#PROVIDER_IAM_SETTINGS
Serverless: Adding Python requirements helper to …
Serverless: Generated requirements from /opt/app/requirements.txt in /opt/app/.serverless/requirements.txt…
Serverless: Using static cache of requirements found at /root/.cache/serverless-python-requirements/5c3_slspyc …
Serverless: Zipping required Python packages for …
Serverless: Using Python specified in “runtime”: python3.7
Serverless: Packaging Python WSGI handler…
Serverless: Packaging service…
Serverless: Excluding development dependencies…
Serverless: Removing Python requirements helper from …
Serverless: Injecting required Python packages to package…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading artifacts…
Serverless: Uploading service app.zip file to S3 (21.41 MB)…
Serverless: Validating template…
Serverless: Creating Stack…
Serverless: Checking Stack create progress…
…
Serverless: Operation failed!
Serverless: View the full error output: /cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3394481%3Astack%2Fdjango-aws-lambda-production%2-beee-11eb-baa0-12

Serverless Error ----------------------------------------

An error occurred: AppLambdaFunction - Properties validation failed for resource AppLambdaFunction with message:
#/Role: failed validation constraint for keyword [pattern].

Get Support --------------------------------------------
Docs: docs.serverless.com
Bugs: /serverless/serverless/issues
Issues:

Your Environment Information ---------------------------
Operating System: linux
Node Version: 14.17.0
Framework Version: 2.43.1
Plugin Version: 5.1.3
SDK Version: 4.2.2
Components Version: 3.10.1

**Comment by VadymKhodak** [comment]
Hi @diegoug 

Have you changed `provider.role` to your role [here](ere https://github.com/VadymKhodak/django-aws-lambda/blob/master/serverless.yaml#L35)?

**Comment by diegoug** [comment]
Yes! @VadymKhodak  worked, in fact I had to configure the fields of the keys <>, but now I have problems with the configuration with the permissions and the vpc in aws, which is not specified in the tutorial, I am new to the aws platform and it can be seen a bit complex but I am solving it as the problems appear, if I get stuck I will surely open another thread if there is not if there is no problem, thank you.

**Comment by VadymKhodak** [comment]
@diegoug Have you seen my other blog posts regarding preparing AWS infra?
https://blog.vadymkhodak.com/deploy-django-app-on-aws-lambda-using-serverless-part-2
https://blog.vadymkhodak.com/deploying-a-django-project-on-aws-lambda-using-serverless-part-3

**Comment by diegoug** [comment]
@VadymKhodak thanks for the advice, I thought that I could solve it just messing around but it is more difficult than I thought, even with your advice I deconfigured the default options, to solve the permissions of the server deployment I had to follow your post 2 and configure these permissions to deploy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:*",
                "ec2:*",
                "apigateway:*",
                "logs:*",
                "lambda:*",
                "cloudformation:*",
                "iam:*"
            ],
            "Resource": "*"
        }
    ]
}
```

and so that django can send the statics I found these permissions on the internet

```
{
    "Version": "2008-10-17",
    "Id": "StaticAndMediaPermissions",
    "Statement": [
        {
            "Sid": "AllowAnybodyToGetBucketLocation",
            "Effect": "Allow",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::nodejs-serverless-bucket"
        },
        {
            "Sid": "AllowCollectstaticUserToListStaticAndMediaDirectories",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::nodejs-serverless-bucket",
                "arn:aws:s3:::nodejs-serverless-bucket/media",
                "arn:aws:s3:::nodejs-serverless-bucket/static"
            ]
        },
        {
            "Sid": "AllowCollectstaticUserAccessToAllObjectsInStaticAndMediaDirectories",
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObjectAcl",
                "s3:ListMultipartUploadParts",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::nodejs-serverless-bucket/media/*",
                "arn:aws:s3:::nodejs-serverless-bucket/static/*"
            ]
        }
    ]
}
```

The truth is that although I managed to configure aws for the deployment, I did it without knowing well what I was doing in some parts, I have a few doubts to be able to mount a django and see the result well, for example, how to point a namechimp domain? and understand well in detail how the essential parts work so that django works correctly, also I would like to set up a serverless micro service system in the future, thanks to you for the tutorials, they are excellent.
